forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/stdlib', '4.24.0'
mod 'thias/sysctl', '1.0.6'
mod 'puppet-unattended_upgrades', '3.2.1'
mod 'puppetlabs-apt', '6.0.0'
mod 'puppet/archive', '3.2.1'
mod 'puppetlabs/translate', '1.2.0'
mod 'alexharvey-firewall_multi', '1.12.0'
mod 'puppetlabs-firewall', '1.15.1'
mod 'saz-resolv_conf', '4.1.0'
mod 'LeLutin-fail2ban', '3.1.0'
mod 'hetzner-needrestart', '1.0.3'
mod 'oxc-rspamd', '1.1.0'
